# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a3522fe19addd2fc84eceb29bd883681c3485f35fbd6fa13360f91768d85a7b2e286e475bed7c0bac4d57ceee7b961749070e327ca10224d401857cbb3329d3

test:
  secret_key_base: 50899c87df4f52356d30ef054c6f8c9a5b11f8e2c9f15b36274022bfcd47e669f5b3552430f32f6183220b6cf382e451de2e0a1aab5a61b58e14a509713dd234

staging:
  secret_key_base: 50899c87df4f52356d30ef054c6f8c9a5b11f8e2c9f15b36274022bfcd47e669f5b3552430f32f6183220b6cf382e451de2e0a1aab5a61b58e14a509713dd234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
